<a href="https://colab.research.google.com/github/ThanikPimpiban/mulitivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Function

python

    def function_name(_Input_) :

       do_something with _Input_ to get _Output

       return _Output

function ประกอบไปด้วย 4 ส่วน

  1.บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name () : (ขาดไม่ได้)

  2.กำหนดตัวแปรที่จะเป็น input (ขาดได้)

  3.ส่วนประมวลผล do_something with to get output (ขาดไม่ได้)

  4.ส่วน return output

In [ ]:
def x1_1(name,surname,ID) :
      st= f'ชื่อ  {name} นามสกุล {surname} ID {ID}'
      return st 
x1_1('thanik','pimpiban','623021049-1')

'ชื่อ  thanik นามสกุล pimpiban ID 623021049-1'

ฟังก์ชั่นไม่จำเป็นต้องมี output

In [ ]:
def Pi():
  return 3.14159265359

In [ ]:
Pi()*(1.2*2)

7.539822368616

In [ ]:
op2 = x1_1('thanik','pimpiban','623021049-1')

In [ ]:
print(op2)

ชื่อ  thanik นามสกุล pimpiban ID 623021049-1


## input ของ funtion ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default) เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_default(name, surname, ID, grade='F'):
   st= f'ชื่อ  {name} นามสกุล {surname} ID {ID}'
   print(st)
   st2= f'เกรด >>>>> {grade}'
   print(st2)

In [ ]:
print_default('thanik','pimpiban','623021049-1')

ชื่อ  thanik นามสกุล pimpiban ID 623021049-1
เกรด >>>>> F


In [ ]:
def print_default(name, surname, ID, grade='F'):
   st= f'ชื่อ  {name} นามสกุล {surname} ID {ID}'
   print(st)
   st2= f'เกรด >>>>> {grade}'
   print(st2)

**เราสามารถเรียก FN โดยใช้ชื่อตัวแปรของ FN ช่วยได้**

In [ ]:
x1_1(ID='623021049-1',name='thanik',surname='pimpiban')

'ชื่อ  thanik นามสกุล pimpiban ID 623021049-1'

# **การบ้าน HW3**

ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [ ]:
def time(tx):
  h1=  int (tx.split('-')[0])*3600
  m1= int (tx.split('-')[1])*60
  s1 = int (tx.split('-')[2])
  ss = h1+m1+s1
  print("แปลงเป็นวินาทีได้ = ",ss," วินาที")
  


In [ ]:
time('14-15-31')    # ข้อ1

แปลงเป็นวินาทีได้ =  51331  วินาที


In [ ]:
time('13-00-01')     #ข้อ2

แปลงเป็นวินาทีได้ =  46801  วินาที


In [ ]:
time('05-49-44')      #ข้อ3

แปลงเป็นวินาทีได้ =  20984  วินาที


In [ ]:
time('00-00-16')      #ข้อ4

แปลงเป็นวินาทีได้ =  16  วินาที


**เสร็จการบ้าน**

ไม่เอา ~pandas~

numpy คือ package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

์num + py คือ number + python

การใช้ package

1. 'import'   'ชื่อ package'   #เรียกใช้ package
2.ชื่อ package   ชื่อ function #เรียกใช้ function


In [19]:
import numpy

สร้าง Numpy

In [25]:
mat_ex1 = numpy.array([[5.2,3,0,4.5],[9,1,0,0.3]]) 
print(mat_ex1)

[[5.2 3.  0.  4.5]
 [9.  1.  0.  0.3]]


In [30]:
mat_ex1[1,1]      #[แถว,หลัก]

1.0

ถ้าไม่มี numpy array 

In [38]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [42]:
list_ex1[1][1]

0.1

In [43]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix operation 

data 2 แบบ -> matrix (array 2D) , scalar(ค่าคงที่)

In [44]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


# บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกกัน
(หน้าตาของ matrix ต้องเหมือนกัน)

In [46]:
mat_ex3 = mat_ex1 + mat_ex2 
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2 
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [47]:
mat_ex0 = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


การตรวจสอบรูปร่างของ matrix

In [49]:
mat_ex3.shape

(2, 3)

In [55]:
mat_ex3.shape[0]

2

#คูณ matrix
(หลักของ matrix ตัวข้างหน้า ต้องเท่ากับแถวของ Matrix ตัวข้างหลัง)

dot product((AAA,x)(x,ZZZ)) = (AAA,ZZZ)

In [77]:
mat_w1 = numpy.array([[1,2,3],[3,2,1]])
mat_w2 = numpy.array([[3,2,1],[1,2,3]])

ValueError: ignored

# Transpose กลับแถวเป็นหลัก กลับหลักเป็นแถว

matrix.T

In [84]:
mat_ex1.T.shape


(3, 2)

In [86]:
mat_ex2.shape

(2, 3)

In [81]:
numpy.dot(mat_ex1,mat_ex2.T)  #(2,3).(3,2)


array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

# HW4 อธิบายการหา Determinant และ Inverse matrix (รูป และ อธิบาย)